---
# has no effect here, but left in place to make it more obvious
# ansible_group_priority: 10

base_package_list:
  - curl
  - wget
  - screen
  - netcat-traditional
  - sudo
  - vim
  - unzip
  - htop

# Storage Volume stuff
lvm_thin_pool:
  name: vm_pool
  vg_name: vgchuebel01
  size: 200g

lvm_volumes:
  - vg: vgchuebel01
    lv_name: dir_storage
    size: 100g
    mount_path: /mnt/dir_storage

# ntp stuff
ntp_manage_config: true
ntp_servers:
  - 0.ch.pool.ntp.org
  - 1.ch.pool.ntp.org
  - 2.ch.pool.ntp.org
  - 3.ch.pool.ntp.org

# proxmox stuff
pve_group: proxmox
pve_reboot_on_kernel_update: false
pve_clustername: pfuetze
pve_cluster_clustername: pfuetze
pve_cluster_enabled: false
pve_ssl_letsencrypt: false
pve_ceph_enabled: false
pve_zfs_enabled: false

pve_groups:
  - name: admin
    comment: me, myself and I
pve_acls:
  - path: /
    roles: ["Administrator"]
    groups: ["admin"]

# users configured here using the pam realm need to be created on the machine first. 
# lea.proxmox only creates the user in proxmox but not on the host it self
pve_users:
  - name: gigu@pam
    email: gigu-proxmox@clauss.swiss
    firstname: Severin
    lastname: Clauss
    groups: ["admin"]

pve_storages:
  - name: vm_storage
    type: lvmthin
    content: ["images", "rootdir"]
    vgname: vgchuebel01
    thinpool: vm_pool
  - name: dir_storage
    type: dir
    content: ["vztmpl", "iso", "backup", "snippets"]
    path: /mnt/dir_storage
